export const peaks = [
  {
    name: "Palenica Białczańska",
    startPoint: true,
    lat: 49.254544,
    lng: 20.102976,
    elevation: 1025,
    routes: [
      {
        id: 1,
        name: "Palenica Białczańska - Morskie Oko",
        gpx: "/gpx/PalenicaBiałczańska-MorskieOko.gpx",
        time: "2:22h",
        length: "7.8km",
        difficulty: "Łatwy",
        mountain_range: "Tatry Wysokie",
        elevation_gain: 415,
      },
      {
        id: 3,
        name: "Rysy",
        gpx: "/gpx/PalenicaBiałczańska-Rysy.gpx",
        time: "6:38h",
        length: "12.8km",
        difficulty: "Bardzo Trudny",
        mountain_range: "Tatry Wysokie",
        elevation_gain: 1519,
      },
    ],
  },
  {
    name: "Morskie Oko",
    lat: 49.201182,
    lng: 20.070832,
    elevation: 1987,
    routes: [
      {
        id: 1,
        name: "Palenica Białczańska - Morskie Oko",
        gpx: "/gpx/PalenicaBiałczańska-MorskieOko.gpx",
        time: "2:22h",
        length: "7.8km",
        difficulty: "Łatwy",
        mountain_range: "Tatry Wysokie",
        elevation_gain: 415,
      },
    ],
  },
  {
    name: "Rysy",
    lat: 49.179575,
    lng: 20.088108,
    elevation: 2503,
    routes: [
      {
        id: 3,
        name: "Rysy",
        gpx: "/gpx/PalenicaBiałczańska-Rysy.gpx",
        time: "6:38h",
        length: "12.8km",
        difficulty: "Bardzo Trudny",
        mountain_range: "Tatry Wysokie",
        elevation_gain: 1519,
      },
    ],
  },
  {
    name: "Kasprowy Wierch",
    lat: 49.231,
    lng: 19.9817,
    elevation: 1987,
    routes: [
      {
        id: 4,
        name: "Kuźnice - Kasprowy Wierch",
        gpx: "/gpx/kuznice-kasprowy.gpx",
        time: "7:24h",
        length: "13km",
        difficulty: "Średnie",
        mountain_range: "Tatry Wysokie",
        elevation_gain: 962,
      },
    ],
  },
  {
    name: "Kuźnice",
    startPoint: true,
    lat: 49.269497,
    lng: 19.980522,
    elevation: 1010,
    routes: [
      {
        id: 2,
        name: "Kuźnice - Giewont",
        gpx: "/gpx/kuznice-giewont.gpx",
        time: "7:08h",
        length: "12.7km",
        difficulty: "Trudny",
        mountain_range: "Tatry Zachodnie",
        elevation_gain: 869,
      },
      {
        id: 4,
        name: "Kuźnice - Kasprowy Wierch",
        gpx: "/gpx/kuznice-kasprowy.gpx",
        time: "7:24h",
        length: "13km",
        difficulty: "Średnie",
        mountain_range: "Tatry Wysokie",
        elevation_gain: 962,
      },
    ],
  },
  {
    name: "Giewont",
    lat: 49.2509584,
    lng: 19.9340969,
    elevation: 1894,
    routes: [
      {
        id: 2,
        name: "Kuźnice - Giewont",
        gpx: "/gpx/kuznice-giewont.gpx",
        time: "7:08h",
        length: "12.7km",
        difficulty: "Trudny",
        mountain_range: "Tatry Zachodnie",
        elevation_gain: 869,
      },
    ],
  },
];
