export const peaks = [
  {
    name: "Palenica Białczańska",
    startPoint: true,
    lat: 49.254544,
    lng: 20.102976,
    elevation: 1025,
    routes: [
      {
        id: 1,
        name: "Palenica Białczańska - Morskie Oko",
        gpx: "/gpx/PalenicaBiałczańska-MorskieOko.gpx",
        time: "2:22h",
        length: "7.8km",
        difficulty: "Łatwy",
        skill_level: "Początkujący",
        wheelchair_accessible: "Tak",
        suitable_for_seniors: "Tak",
        child_friendly: "Tak",
        mountain_range: "Tatry Wysokie",
        elevation_gain: 415,
      },
      {
        id: 3,
        name: "Palenica Białczańska - Rysy",
        gpx: "/gpx/PalenicaBiałczańska-Rysy.gpx",
        time: "6:38h",
        length: "12.8km",
        difficulty: "Bardzo Trudny",
        skill_level: "Zaawansowany",
        wheelchair_accessible: "Nie",
        suitable_for_seniors: "Nie",
        child_friendly: "Nie",
        mountain_range: "Tatry Wysokie",
        elevation_gain: 1519,
      },
      {
        id: 10,
        name: "Palenica Białczańska - Szpiglasowy Wierch",
        gpx: "/gpx/PalenicaBiałczańska-SzpiglasowyWierch.gpx",
        time: "5:25h",
        length: "11.4km",
        difficulty: "Trudny",
        skill_level: "Zaawansowany",
        wheelchair_accessible: "Nie",
        suitable_for_seniors: "Nie",
        child_friendly: "Nie",
        mountain_range: "Tatry Wysokie",
        elevation_gain: 1120,
      },
      {
        id: 19,
        name: "Palenica Białczańska - Dolina Pięciu Stawów Polskich",
        gpx: "/gpx/PalenicaBiałczańska-DolinaPięciuStawówPolskich.gpx",
        time: "3:25h",
        length: "8.8km",
        difficulty: "Średni",
        skill_level: "Początkujący",
        wheelchair_accessible: "Tak",
        suitable_for_seniors: "Nie",
        child_friendly: "Tak",
        mountain_range: "Tatry Wysokie",
        elevation_gain: 700,
      },
    ],
  },
  {
    name: "Morskie Oko",
    lat: 49.201182,
    lng: 20.070832,
    elevation: 1393,
    routes: [
      {
        id: 1,
        name: "Palenica Białczańska - Morskie Oko",
        gpx: "/gpx/PalenicaBiałczańska-MorskieOko.gpx",
        time: "2:22h",
        length: "7.8km",
        difficulty: "Łatwy",
        skill_level: "Początkujący",
        wheelchair_accessible: "Tak",
        suitable_for_seniors: "Tak",
        child_friendly: "Tak",
        mountain_range: "Tatry Wysokie",
        elevation_gain: 415,
      },
    ],
  },
  {
    name: "Rysy",
    lat: 49.179575,
    lng: 20.088108,
    elevation: 2503,
    routes: [
      {
        id: 3,
        name: "Palenica Białczańska - Rysy",
        gpx: "/gpx/PalenicaBiałczańska-Rysy.gpx",
        time: "6:38h",
        length: "12.8km",
        difficulty: "Bardzo Trudny",
        skill_level: "Zaawansowany",
        wheelchair_accessible: "Nie",
        suitable_for_seniors: "Nie",
        child_friendly: "Nie",
        mountain_range: "Tatry Wysokie",
        elevation_gain: 1519,
      },
    ],
  },
  {
    name: "Szpiglasowy Wierch",
    lat: 49.197291,
    lng: 20.040106,
    elevation: 2172,
    routes: [
      {
        id: 10,
        name: "Palenica Białczańska - Szpiglasowy Wierch",
        gpx: "/gpx/PalenicaBiałczańska-SzpiglasowyWierch.gpx",
        time: "5:25h",
        length: "11.4km",
        difficulty: "Trudny",
        skill_level: "Zaawansowany",
        wheelchair_accessible: "Nie",
        suitable_for_seniors: "Nie",
        child_friendly: "Nie",
        mountain_range: "Tatry Wysokie",
        elevation_gain: 1120,
      },
    ],
  },
  {
    name: "Dolina Pięciu Stawów Polskich",
    lat: 49.209721,
    lng: 20.029995,
    elevation: 1668,
    routes: [
      {
        id: 19,
        name: "Palenica Białczańska - Dolina Pięciu Stawów Polskich",
        gpx: "/gpx/PalenicaBiałczańska-DolinaPięciuStawówPolskich.gpx",
        time: "3:25h",
        length: "8.8km",
        difficulty: "Średni",
        skill_level: "Początkujący",
        wheelchair_accessible: "Tak",
        suitable_for_seniors: "Nie",
        child_friendly: "Tak",
        mountain_range: "Tatry Wysokie",
        elevation_gain: 700,
      },
    ],
  },
  {
    name: "Kasprowy Wierch",
    lat: 49.231,
    lng: 19.9817,
    elevation: 1987,
    routes: [
      {
        id: 4,
        name: "Kuźnice - Kasprowy Wierch",
        gpx: "/gpx/kuznice-kasprowy.gpx",
        time: "7:24h",
        length: "13km",
        difficulty: "Średni",
        skill_level: "Średniozaawansowany",
        wheelchair_accessible: "Nie",
        suitable_for_seniors: "Nie",
        child_friendly: "Tak",
        mountain_range: "Tatry Wysokie",
        elevation_gain: 962,
      },
    ],
  },
  {
    name: "Kuźnice",
    startPoint: true,
    lat: 49.269497,
    lng: 19.980522,
    elevation: 1010,
    routes: [
      {
        id: 2,
        name: "Kuźnice - Giewont",
        gpx: "/gpx/kuznice-giewont.gpx",
        time: "7:08h",
        length: "12.7km",
        difficulty: "Trudny",
        skill_level: "Średniozaawansowany",
        wheelchair_accessible: "Nie",
        suitable_for_seniors: "Nie",
        child_friendly: "Nie",
        mountain_range: "Tatry Zachodnie",
        elevation_gain: 869,
      },
      {
        id: 4,
        name: "Kuźnice - Kasprowy Wierch",
        gpx: "/gpx/kuznice-kasprowy.gpx",
        time: "7:24h",
        length: "13km",
        difficulty: "Średni",
        skill_level: "Średniozaawansowany",
        wheelchair_accessible: "Nie",
        suitable_for_seniors: "Nie",
        child_friendly: "Tak",
        mountain_range: "Tatry Wysokie",
        elevation_gain: 962,
      },
      {
        id: 7,
        name: "Kuźnice - Kozi Wierch",
        gpx: "/gpx/Kuznice-KoziWierch.gpx",
        time: "7:19h",
        length: "10.3km",
        difficulty: "Bardzo Trudny",
        skill_level: "Zaawansowany",
        wheelchair_accessible: "Nie",
        suitable_for_seniors: "Nie",
        child_friendly: "Nie",
        mountain_range: "Tatry Zachodnie",
        elevation_gain: 1350,
      },
      {
        id: 8,
        name: "Kuźnice - Świnica",
        gpx: "/gpx/Kuznice-Swinica.gpx",
        time: "5:16h",
        length: "9km",
        difficulty: "Bardzo Trudny",
        skill_level: "Zaawansowany",
        wheelchair_accessible: "Nie",
        suitable_for_seniors: "Nie",
        child_friendly: "Nie",
        mountain_range: "Tatry Wysokie",
        elevation_gain: 1220,
      },
      {
        id: 9,
        name: "Kuźnice - Kościelec",
        gpx: "/gpx/Kuznice-Koscielec.gpx",
        time: "4:26h",
        length: "8.7km",
        difficulty: "Trudny",
        skill_level: "Zaawansowany",
        wheelchair_accessible: "Nie",
        suitable_for_seniors: "Nie",
        child_friendly: "Nie",
        mountain_range: "Tatry Wysokie",
        elevation_gain: 940,
      },
      {
        id: 11,
        name: "Kuźnice - Nosal",
        gpx: "/gpx/Kuznice-Nosal.gpx",
        time: "0:43h",
        length: "1.6km",
        difficulty: "Łatwy",
        skill_level: "Początkujący",
        wheelchair_accessible: "Tak",
        suitable_for_seniors: "Nie",
        child_friendly: "Tak",
        mountain_range: "Tatry Zachodnie",
        elevation_gain: 300,
      },
    ],
  },
  {
    name: "Giewont",
    lat: 49.2509584,
    lng: 19.9340969,
    elevation: 1894,
    routes: [
      {
        id: 2,
        name: "Kuźnice - Giewont",
        gpx: "/gpx/kuznice-giewont.gpx",
        time: "7:08h",
        length: "12.7km",
        difficulty: "Trudny",
        skill_level: "Średniozaawansowany",
        wheelchair_accessible: "Nie",
        suitable_for_seniors: "Nie",
        child_friendly: "Nie",
        mountain_range: "Tatry Zachodnie",
        elevation_gain: 869,
      },
    ],
  },
  {
    name: "Toporowa Cyrhla",
    startPoint: true,
    lat: 49.287555,
    lng: 20.011681,
    elevation: 1020,
    routes: [
      {
        id: 5,
        name: "Toporowa Cyrhla - Gęsia Szyja",
        gpx: "/gpx/ToporowaCyrhla-GesiaSzyja.gpx",
        time: "3:36h",
        length: "10km",
        difficulty: "Łatwy",
        skill_level: "Początkujący",
        wheelchair_accessible: "Nie",
        suitable_for_seniors: "Tak",
        child_friendly: "Tak",
        mountain_range: "Tatry Zachodnie",
        elevation_gain: 665,
      },
      {
        id: 16,
        name: "Toporowa Cyrhla - Wielki Kopieniec",
        gpx: "/gpx/ToporowaCyrhla-WielkiKopieniec.gpx",
        time: "1:05h",
        length: "2.3km",
        difficulty: "Łatwy",
        skill_level: "Początkujący",
        wheelchair_accessible: "Nie",
        suitable_for_seniors: "Tak",
        child_friendly: "Tak",
        mountain_range: "Tatry Zachodnie",
        elevation_gain: 350,
      },
    ],
  },
  {
    name: "Gęsia Szyja",
    lat: 49.259054,
    lng: 20.076541,
    elevation: 1489,
    routes: [
      {
        id: 5,
        name: "Toporowa Cyrhla - Gęsia Szyja",
        gpx: "/gpx/ToporowaCyrhla-GesiaSzyja.gpx",
        time: "3:36h",
        length: "10km",
        difficulty: "Łatwy",
        skill_level: "Początkujący",
        wheelchair_accessible: "Nie",
        suitable_for_seniors: "Tak",
        child_friendly: "Tak",
        mountain_range: "Tatry Zachodnie",
        elevation_gain: 665,
      },
    ],
  },
  {
    name: "Wielki Kopieniec",
    lat: 49.271693,
    lng: 20.016299,
    elevation: 1328,
    routes: [
      {
        id: 16,
        name: "Toporowa Cyrhla - Wielki Kopieniec",
        gpx: "/gpx/ToporowaCyrhla-WielkiKopieniec.gpx",
        time: "1:05h",
        length: "2.3km",
        difficulty: "Łatwy",
        skill_level: "Początkujący",
        wheelchair_accessible: "Nie",
        suitable_for_seniors: "Tak",
        child_friendly: "Tak",
        mountain_range: "Tatry Zachodnie",
        elevation_gain: 350,
      },
    ],
  },
  {
    name: "Siwa Polana",
    startPoint: true,
    lat: 49.282661,
    lng: 19.841692,
    elevation: 910,
    routes: [
      {
        id: 6,
        name: "Dolina Chochołowska - Grześ",
        gpx: "/gpx/DolinaChocholowska-Grzes.gpx",
        time: "4:00h",
        length: "10.1km",
        difficulty: "Łatwy",
        skill_level: "Początkujący",
        wheelchair_accessible: "Nie",
        suitable_for_seniors: "Tak",
        child_friendly: "Tak",
        mountain_range: "Tatry Zachodnie",
        elevation_gain: 658,
      },
    ],
  },
  {
    name: "Grześ",
    lat: 49.236584,
    lng: 19.766779,
    elevation: 1653,
    routes: [
      {
        id: 6,
        name: "Dolina Chochołowska - Grześ",
        gpx: "/gpx/DolinaChocholowska-Grzes.gpx",
        time: "4:00h",
        length: "10.1km",
        difficulty: "Łatwy",
        skill_level: "Początkujący",
        wheelchair_accessible: "Nie",
        suitable_for_seniors: "Tak",
        child_friendly: "Tak",
        mountain_range: "Tatry Zachodnie",
        elevation_gain: 658,
      },
    ],
  },

  {
    name: "Dolina Kościeliska",
    startPoint: true,
    lat: 49.275474,
    lng: 19.868932,
    elevation: 927,
    routes: [
      {
        id: 21,
        name: "Dolina Kościeliska do schroniska Ornak",
        gpx: "/gpx/DolinaKościeliskadoschroniskaOrnak.gpx",
        time: "1:35h",
        length: "5.6km",
        difficulty: "Łatwy",
        skill_level: "Początkujący",
        wheelchair_accessible: "Tak",
        suitable_for_seniors: "Tak",
        child_friendly: "Tak",
        mountain_range: "Tatry Zachodnie",
        elevation_gain: 200,
      },
    ],
  },
  {
    name: "Zakopane",
    startPoint: true,
    lat: 49.278708,
    lng: 19.93862,
    elevation: 840,
    routes: [
      {
        id: 14,
        name: "Dolina Strążyska - Polana Strążyska",
        gpx: "/gpx/DolinaStrążyska-PolanaStrążyska.gpx",
        time: "0:40h",
        length: "1.9km",
        difficulty: "Łatwy",
        skill_level: "Początkujący",
        wheelchair_accessible: "Tak",
        suitable_for_seniors: "Tak",
        child_friendly: "Tak",
        mountain_range: "Tatry Zachodnie",
        elevation_gain: 130,
      },
    ],
  },
  {
    name: "Psia Trawka",
    startPoint: true,
    lat: 49.269761,
    lng: 20.036569,
    elevation: 1180,
    routes: [
      {
        id: 13,
        name: "Psia Trawka - Hala Gąsienicowa",
        gpx: "/gpx/PsiaTrawka-HalaGąsienicowa.gpx",
        time: "1:20h",
        length: "4.7km",
        difficulty: "Łatwy",
        skill_level: "Początkujący",
        wheelchair_accessible: "Tak",
        suitable_for_seniors: "Nie",
        child_friendly: "Tak",
        mountain_range: "Tatry Wysokie",
        elevation_gain: 280,
      },
    ],
  },
  {
    name: "Hala Gąsienicowa",
    lat: 49.241466,
    lng: 20.00176,
    elevation: 1500,
    routes: [
      {
        id: 13,
        name: "Psia Trawka - Hala Gąsienicowa",
        gpx: "/gpx/PsiaTrawka-HalaGąsienicowa.gpx",
        time: "1:20h",
        length: "4.7km",
        difficulty: "Łatwy",
        skill_level: "Początkujący",
        wheelchair_accessible: "Tak",
        suitable_for_seniors: "Nie",
        child_friendly: "Tak",
        mountain_range: "Tatry Wysokie",
        elevation_gain: 280,
      },
    ],
  },
  {
    name: "Wierch Poroniec",
    startPoint: true,
    lat: 49.284499,
    lng: 20.112998,
    elevation: 1080,
    routes: [
      {
        id: 15,
        name: "Wierch Poroniec - Rusinowa Polana",
        gpx: "/gpx/WierchPoroniec-RusinowaPolana.gpx",
        time: "1:00h",
        length: "3.2km",
        difficulty: "Łatwy",
        skill_level: "Początkujący",
        wheelchair_accessible: "Tak",
        suitable_for_seniors: "Tak",
        child_friendly: "Tak",
        mountain_range: "Tatry Zachodnie",
        elevation_gain: 150,
      },
    ],
  },
  {
    name: "Rusinowa Polana",
    lat: 49.262857,
    lng: 20.09029,
    elevation: 1200,
    routes: [
      {
        id: 15,
        name: "Wierch Poroniec - Rusinowa Polana",
        gpx: "/gpx/WierchPoroniec-RusinowaPolana.gpx",
        time: "1:00h",
        length: "3.2km",
        difficulty: "Łatwy",
        skill_level: "Początkujący",
        wheelchair_accessible: "Tak",
        suitable_for_seniors: "Tak",
        child_friendly: "Tak",
        mountain_range: "Tatry Zachodnie",
        elevation_gain: 150,
      },
    ],
  },
  {
    name: "Dolina Białego",
    startPoint: true,
    lat: 49.277887,
    lng: 19.95714,
    elevation: 915,
    routes: [
      {
        id: 18,
        name: "Dolina Białego - Polana Kalatówki",
        gpx: "/gpx/DolinaBiałego-PolanaKalatówki.gpx",
        time: "2:28h",
        length: "5.8km",
        difficulty: "Średni",
        skill_level: "Początkujący",
        wheelchair_accessible: "Tak",
        suitable_for_seniors: "Nie",
        child_friendly: "Nie",
        mountain_range: "Tatry Zachodnie",
        elevation_gain: 300,
      },
    ],
  },
  {
    name: "Polana Kalatówki",
    lat: 49.256331,
    lng: 19.968667,
    elevation: 1198,
    routes: [
      {
        id: 18,
        name: "Dolina Białego - Polana Kalatówki",
        gpx: "/gpx/DolinaBiałego-PolanaKalatówki.gpx",
        time: "2:28h",
        length: "5.8km",
        difficulty: "Średni",
        skill_level: "Początkujący",
        wheelchair_accessible: "Tak",
        suitable_for_seniors: "Nie",
        child_friendly: "Nie",
        mountain_range: "Tatry Zachodnie",
        elevation_gain: 300,
      },
    ],
  },

  {
    name: "Kozi Wierch",
    lat: 49.218317,
    lng: 20.028705,
    elevation: 2291,
    routes: [
      {
        id: 7,
        name: "Kuźnice - Kozi Wierch",
        gpx: "/gpx/Kuznice-KoziWierch.gpx",
        time: "7:19h",
        length: "10.3km",
        difficulty: "Bardzo Trudny",
        skill_level: "Zaawansowany",
        wheelchair_accessible: "Nie",
        suitable_for_seniors: "Nie",
        child_friendly: "Nie",
        mountain_range: "Tatry Zachodnie",
        elevation_gain: 1350,
      },
    ],
  },
  {
    name: "Świnica",
    lat: 49.219421,
    lng: 20.009306,
    elevation: 2301,
    routes: [
      {
        id: 8,
        name: "Kuźnice - Świnica",
        gpx: "/gpx/Kuznice-Swinica.gpx",
        time: "5:16h",
        length: "9km",
        difficulty: "Bardzo Trudny",
        skill_level: "Zaawansowany",
        wheelchair_accessible: "Nie",
        suitable_for_seniors: "Nie",
        child_friendly: "Nie",
        mountain_range: "Tatry Wysokie",
        elevation_gain: 1220,
      },
    ],
  },
  {
    name: "Kościelec",
    lat: 49.225179,
    lng: 20.014583,
    elevation: 2155,
    routes: [
      {
        id: 9,
        name: "Kuźnice - Kościelec",
        gpx: "/gpx/Kuznice-Koscielec.gpx",
        time: "4:26h",
        length: "8.7km",
        difficulty: "Trudny",
        skill_level: "Zaawansowany",
        wheelchair_accessible: "Nie",
        suitable_for_seniors: "Nie",
        child_friendly: "Nie",
        mountain_range: "Tatry Wysokie",
        elevation_gain: 940,
      },
    ],
  },
  {
    name: "Nosal",
    lat: 49.276484,
    lng: 19.9896,
    elevation: 1206,
    routes: [
      {
        id: 11,
        name: "Kuźnice - Nosal",
        gpx: "/gpx/Kuznice-Nosal.gpx",
        time: "0:43h",
        length: "1.6km",
        difficulty: "Łatwy",
        skill_level: "Początkujący",
        wheelchair_accessible: "Tak",
        suitable_for_seniors: "Nie",
        child_friendly: "Tak",
        mountain_range: "Tatry Zachodnie",
        elevation_gain: 300,
      },
    ],
  },
  {
    name: "Polana Strążyska",
    lat: 49.263028,
    lng: 19.929702,
    elevation: 1042,
    routes: [
      {
        id: 14,
        name: "Dolina Strążyska - Polana Strążyska",
        gpx: "/gpx/DolinaStrążyska-PolanaStrążyska.gpx",
        time: "0:40h",
        length: "1.9km",
        difficulty: "Łatwy",
        skill_level: "Początkujący",
        wheelchair_accessible: "Tak",
        suitable_for_seniors: "Tak",
        child_friendly: "Tak",
        mountain_range: "Tatry Zachodnie",
        elevation_gain: 130,
      },
    ],
  },
  {
    name: "Schronisko na Hali Ornak",
    lat: 49.228942,
    lng: 19.85881,
    elevation: 1100,
    routes: [
      {
        id: 21,
        name: "Dolina Kościeliska do schroniska Ornak",
        gpx: "/gpx/DolinaKościeliskadoschroniskaOrnak.gpx",
        time: "1:35h",
        length: "5.6km",
        difficulty: "Łatwy",
        skill_level: "Początkujący",
        wheelchair_accessible: "Tak",
        suitable_for_seniors: "Tak",
        child_friendly: "Tak",
        mountain_range: "Tatry Zachodnie",
        elevation_gain: 200,
      },
    ],
  },
];
